# Generated by Django 2.2 on 2019-09-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0004_movie_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='about',
            field=models.CharField(default='', max_length=1280),
        ),
    ]
